# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_msg"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "converts any standard scalar type to a string and support unit testing"
categories = ["messages", " testing"]
keywords = ["fortran", "unit testing"]
homepage = "https://github.com/urbanjost/M_msg.git"

[[executable]]
name = "hlp"
source-dir = "app"
main = "hlp.f90"
#link = "z"
[executable.dependencies]
M_io   = { git = "https://github.com/urbanjost/M_io.git" }
