# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_msg"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "converts any standard scalar type to a string"

[library]
source-dir="src"

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

[[test]]
name="demo_str"
source-dir="test/demos/str"
main="str.f90"

[[test]]
name="demo_journal"
source-dir="test/demos/journal"
main="journal.f90"

[[test]]
name="demo_M_journal"
source-dir="test/demos/M_journal"
main="M_journal.f90"

[[test]]
name="demo_assert"
source-dir="test/demos/assert"
main="assert.f90"

[[test]]
name="demo_fstop"
source-dir="test/demos/fstop"
main="fstop.f90"

[[test]]
name="demo_M_verify"
source-dir="test/demos/M_verify"
main="M_verify.f90"

[[test]]
name="demo_pdec"
source-dir="test/demos/pdec"
main="pdec.f90"

[[test]]
name="demo_stderr"
source-dir="test/demos/stderr"
main="stderr.f90"

[[test]]
name="demo_unit_check"
source-dir="test/demos/unit_check"
main="unit_check.f90"

[[test]]
name="demo_unit_check_bad"
source-dir="test/demos/unit_check_bad"
main="unit_check_bad.f90"

[[test]]
name="demo_unit_check_done"
source-dir="test/demos/unit_check_done"
main="unit_check_done.f90"

[[test]]
name="demo_unit_check_good"
source-dir="test/demos/unit_check_good"
main="unit_check_good.f90"

[[test]]
name="demo_unit_check_msg"
source-dir="test/demos/unit_check_msg"
main="unit_check_msg.f90"

[[test]]
name="demo_unit_check_start"
source-dir="test/demos/unit_check_start"
main="unit_check_start.f90"

[[test]]
name="demo_accdig"
source-dir="test/demos/accdig"
main="accdig.f90"

[[test]]
name="demo_almost"
source-dir="test/demos/almost"
main="almost.f90"

[[test]]
name="demo_dp_accdig"
source-dir="test/demos/dp_accdig"
main="dp_accdig.f90"

[[test]]
name="demo_in_margin"
source-dir="test/demos/in_margin"
main="in_margin.f90"
