/home/urbanjs/venus/V600/github/M_msg/src/M_journal.f90 File Reference
Data Types
interface m_journal::journal
NAME
journal(3f) - [M_journal] provides public message routine, no paging or graphic mode change (LICENSE:PD)
SYNOPSIS
Modules
module m_time
module m_journal
NAME
M_journal(3fm) - [M_journal] write program messages to stdout and/or a log file (LICENSE:PD)
SYNOPSIS
Functions/Subroutines
subroutine, public m_time::d2j (dat, julian, ierr)
subroutine, public m_time::j2d (dat, julian, ierr)
subroutine, public m_time::d2u (dat, unixtime, ierr)
subroutine, public m_time::u2d (dat, unixtime, ierr)
integer function, public m_time::d2o (dat)
character(len=:) function, allocatable, public m_time::v2mo (imonth)
character(len=:) function, allocatable, public m_time::now (format)
character(len=:) function, allocatable, public m_time::fmtdate (values, format)
subroutine, public m_time::fmtdate_usage (ii)
subroutine, public m_time::dow (values, weekday, day, ierr)
subroutine, public m_time::woy (dat, iso_year, iso_week, iso_weekday, iso_name)
integer function uncorrected_week_of_year (datin)
real(kind=dp) function, public m_time::dj (dat)
integer function, dimension(8), public m_time::jd (julian)
real(kind=dp) function, public m_time::du (dat)
integer function, dimension(8), public m_time::ud (unixtime)
subroutine, public m_time::sys_sleep (wait_seconds)
character(len=:) function, allocatable now_ex (format)
subroutine m_journal::where_write_message (where, msg)
subroutine m_journal::flush_trail ()
subroutine m_journal::set_stdout_lun (iounit)
subroutine m_journal::where_write_message_all (where, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, nospace)
NAME
where_write_message_all(3f) - [M_journal] converts any standard scalar type to a string and calls journal(3f) (LICENSE:PD)
SYNOPSIS
subroutine m_journal::write_message_only (message)
character(len=:) function, allocatable m_journal::now_ex (format)
Variables
integer, parameter, private m_time::dp =kind(0.0d0)
real(kind=dp) m_time::secday =86400.0d0
integer, save, private m_journal::stdout =OUTPUT_UNIT
logical, save m_journal::debug =.false.
integer, save m_journal::last_int =0
Function/Subroutine Documentation
now_ex()
character(len=:) function, allocatable now_ex (character(len=*), intent(in), optional format) [private]
References m_time::now().
uncorrected_week_of_year()
integer function woy::uncorrected_week_of_year (integer, dimension(8), intent(in) datin) [private]
References m_time::d2o(), and m_time::dow().