m_journal Module Reference
NAME
M_journal(3fm) - [M_journal] write program messages to stdout and/or a log file (LICENSE:PD)
SYNOPSIS
Data Types
interface journal
NAME
journal(3f) - [M_journal] provides public message routine, no paging or graphic mode change (LICENSE:PD)
SYNOPSIS
Functions/Subroutines
subroutine where_write_message (where, msg)
subroutine flush_trail ()
subroutine set_stdout_lun (iounit)
subroutine where_write_message_all (where, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, nospace)
NAME
where_write_message_all(3f) - [M_journal] converts any standard scalar type to a string and calls journal(3f) (LICENSE:PD)
SYNOPSIS
subroutine write_message_only (message)
subroutine d2j (dat, julian, ierr)
subroutine j2d (dat, julian, ierr)
subroutine d2u (dat, unixtime, ierr)
subroutine u2d (dat, unixtime, ierr)
integer function d2o (dat)
character(len=:) function, allocatable v2mo (imonth)
character(len=:) function, allocatable now (format)
character(len=:) function, allocatable fmtdate (values, format)
subroutine fmtdate_usage (ii)
subroutine dow (values, weekday, day, ierr)
subroutine woy (dat, iso_year, iso_week, iso_weekday, iso_name)
real(kind=dp) function dj (dat)
integer function, dimension(8) jd (julian)
real(kind=dp) function du (dat)
integer function, dimension(8) ud (unixtime)
subroutine sys_sleep (wait_seconds)
character(len=:) function, allocatable now_ex (format)
Variables
integer, save, private stdout =OUTPUT_UNIT
logical, save debug =.false.
integer, save last_int =0
integer, parameter, private dp =kind(0.0d0)
real(kind=dp) secday =86400.0d0
Detailed Description
NAME
M_journal(3fm) - [M_journal] write program messages to stdout and/or a log file (LICENSE:PD)
SYNOPSIS
use, M_journal , only : journal
DESCRIPTION
For interactive programs in particular it is useful if all messages
go thru the JOURNAL(3f) routine. This makes it easy to write messages
to a log file as well as standard output; to toggle time prefixes
on and off; to turn on and off debug-mode messages; control output
paging and create replayable input journals.

The primary use of JOURNAL(3f) is to create journal files for
interactive programs that can be replayed and/or be used to verify
program executions. Typically, you would echo what the user typed to
the trail file as-is, and write output you write to stdout as comments
to the trail file so that the trail file can easily be read back in
(by ignoring comments). So usually things that are read from user
input are using output with WHERE='T' and output that usually goes
to stdout is written with WHERE='SC' in the JOURNAL(3f) call.

 >      :
 >      :
 > character(len=256) userline, output
 > call journal('O','my_trail_file')  ! open trail file
 >      :
 >      :
 > do
 >    read(*,'(a)',iostat=ios) userline  ! read user input
 >    if(ios.ne.0)exit
 >    ! echo user input to trail file
 >    call journal('T',userline)
 >    ! assume user input causes values i1, i2, and i3 to be calculated
 >    write(output,'(i0,1x,i0,1x)')i1,i2,i3 ! build an output line
 >    ! write output to stdout and as comment to trail file
 >    call journal(output)
 >    !or you can specify the WHERE parameter and up to ten scalar values
 >    call journal('SC','i1=',i1,'i2=',i2,'i3=',i3)
 > enddo

In this example an output line was built with an internal write; but calls
to journal(3f) with numeric values with and without advancing I/O turned on
are often used for simpler output:

   I=10
   R=20.3
   ! write to stdout and trail file without advancing I/O
   call journal('+SC','I=',i)
   call journal('SC','AND R=',r)

writes to the trail file are ignored unless a trail file was opened with

   CALL JOURNAL('O',filename)


So that routines that do their output via JOURNAL(3f) can be used with and
without programs generating trail files. That is, destinations 'T' and 'C'
are ignored unless a trail file has been requested.

With no parameters, the trail file is flushed.
EXAMPLES
The man(1) page for journal(3f) describes all the options for the WHERE field.
In addition to being used to generate a journal, the routine can be used for
producing optional debug messages and timing information.

Sample program for debug messages:

  program demo_journal
  !! showing creating debug messages
  use M_journal, only : journal
  implicit none
  !! produces no output because trail is not on
  call journal('D','*demo* DEBUG MESSAGE 001 IGNORED')
  !! turn on debug messages
  call journal('>','debug on')
  !! produces output on stdout because debug mode
  !! is on but no named trail file
  call journal('D','*demo* DEBUG MESSAGE 002 ON STDOUT')
  !! open trail file
  call journal('O','mytrail.txt')
  !! debug messages now go to the trail file
  call journal('D','*demo* DEBUG MESSAGE 003 TO TRAIL')
  !! close trail file so messages go to stdout again
  call journal('O','')
  !! debug on stdout now
  call journal('D','*demo* DEBUG MESSAGE 004 TO STDOUT')
  call journal('<','debug off')
  !! back to no output from the next message
  call journal('D','*demo* DEBUG MESSAGE 005 IGNORED')
  end program demo_journal
Sample program for trail messages with optional timing information:
program testit use M_journal,only : journal implicit none call journal('a single string A -should be on S')
! add time prefix to output call journal('','Y-M-DTh:m:s.xu:b') call journal('a single string B -should be on S with prefix') call journal('','CPU_TIME: c:CALLS: C: b') ! change time prefix call journal('a single string B-1 -should be on S with prefix') call journal('a single string B-2 -should be on S with prefix') call journal('a single string B-3 -should be on S with prefix') ! Other useful time formats: ! E -- Unix Epoch time ! e -- integer value of Unix Epoch time ! C -- number of times this format is used ! c -- CPU_time(3f) output ! S -- seconds since last use of this format ! k -- CPU time in seconds from system_clock call journal('','') ! turn off time prefix ! call journal('a single string C -should be on S') ! call journal('O','aaa.out') ! turn on trail file call journal('a single string D -should be on SC') call journal('a single string E -should be on SC') call journal('a single string F -should be on SC') call journal('O','') ! turn off trail file ! call journal('a single string G -should be on S') call journal('a single string H -should be on S') call journal('a single string I -should be on S')
! build one line of output with intrinsic scalar values added call journal('+sc','APPEND:') call journal('+sc',' integer', 1234) call journal('+sc',' and real', 1234.5678) call journal('+sc',' and double',1234567890.123456d0) call journal('+sc',' and logical', .true.) call journal('sc','') ! end program testit
AUTHOR
John S. Urban
LICENSE
Public Domain
Function/Subroutine Documentation
d2j()
subroutine m_journal::d2j (integer, dimension(8), intent(in) dat, real(kind=dp), intent(out) julian, integer, intent(out) ierr) [private]
d2o()
integer function m_journal::d2o (integer, dimension(8), intent(in) dat) [private]
References d2u(), and secday.
d2u()
subroutine m_journal::d2u (integer, dimension(8), intent(in) dat, real(kind=dp), intent(out) unixtime, integer, intent(out) ierr) [private]
References d2j(), and secday.
dj()
real(kind=dp) function m_journal::dj (integer, dimension(8), intent(in) dat) [private]
References d2j().
dow()
subroutine m_journal::dow (integer, dimension(8), intent(in) values, integer, intent(out), optional weekday, character*(*), intent(out), optional day, integer, intent(out) ierr) [private]
References d2j().
du()
real(kind=dp) function m_journal::du (integer, dimension(8), intent(in) dat) [private]
References d2u().
flush_trail()
subroutine m_journal::flush_trail () [private]
References where_write_message().
fmtdate()
character(len=:) function, allocatable m_journal::fmtdate (integer, dimension(8), intent(in) values, character(len=*), intent(in) format) [private]
References d2j(), d2o(), d2u(), dow(), v2mo(), and woy().
fmtdate_usage()
subroutine m_journal::fmtdate_usage (integer ii) [private]
j2d()
subroutine m_journal::j2d (integer, dimension(8), intent(out) dat, real(kind=dp), intent(in) julian, integer, intent(out) ierr) [private]
References secday.
jd()
integer function, dimension(8) m_journal::jd (real(kind=dp), intent(in) julian) [private]
References j2d().
now()
character(len=:) function, allocatable m_journal::now (character(len=*), intent(in), optional format) [private]
References fmtdate().
now_ex()
character(len=:) function, allocatable m_journal::now_ex (character(len=*), intent(in), optional format) [private]
References now().
set_stdout_lun()
subroutine m_journal::set_stdout_lun (integer, intent(in) iounit) [private]
References stdout.
sys_sleep()
subroutine m_journal::sys_sleep (integer (c_int) wait_seconds) [private]
u2d()
subroutine m_journal::u2d (integer, dimension(8), intent(out) dat, real(kind=dp), intent(in) unixtime, integer, intent(out) ierr) [private]
References d2j(), j2d(), and secday.
ud()
integer function, dimension(8) m_journal::ud (real(kind=dp), intent(in) unixtime) [private]
References u2d().
v2mo()
character(len=:) function, allocatable m_journal::v2mo (integer, intent(in) imonth) [private]
where_write_message()
subroutine m_journal::where_write_message (character(len=*), intent(in) where, character(len=*), intent(in) msg) [private]
References debug, last_int, now_ex(), and stdout.
where_write_message_all()
subroutine m_journal::where_write_message_all (character(len=*), intent(in) where, class(*), intent(in) g0, class(*), intent(in), optional g1, class(*), intent(in), optional g2, class(*), intent(in), optional g3, class(*), intent(in), optional g4, class(*), intent(in), optional g5, class(*), intent(in), optional g6, class(*), intent(in), optional g7, class(*), intent(in), optional g8, class(*), intent(in), optional g9, logical, intent(in), optional nospace) [private]
NAME
where_write_message_all(3f) - [M_journal] converts any standard scalar type to a string and calls journal(3f) (LICENSE:PD)
SYNOPSIS
subroutine where_write_message_all(where,g0,g1,g2g3,g4,g5,g6,g7,g8,g9,nospace)
character(len=*),intent(in) :: where class(*),intent(in) :: g0 class(*),intent(in),optional :: g1,g2,g3,g4,g5,g6,g7,g8,g9 logical,intent(in),optional :: nospace
DESCRIPTION
where_write_message_all(3f) builds and writes a space-separated string from up to nine scalar values.
OPTIONS
where    string designating where to write message, as with journal(3f)
g0       value to print. May
         be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX,
         or CHARACTER.
g[1-9]   optional additional values to print the value of after g0.
nospace  if nospace=.true., then no spaces are added between values
RETURNS
where_write_message_all description to print
EXAMPLES
Sample program:
program demo_wm_all use M_journal, only : where_write_message_all implicit none end program program demo_wm_all
AUTHOR
John S. Urban
LICENSE
Public Domain
References where_write_message().
woy()
subroutine m_journal::woy (integer, dimension(8), intent(in) dat, integer, intent(out) iso_year, integer, intent(out) iso_week, integer, intent(out) iso_weekday, character(len=10), intent(out) iso_name) [private]
References uncorrected_week_of_year().
write_message_only()
subroutine m_journal::write_message_only (character(len=*), intent(in) message) [private]
References where_write_message().
Variable Documentation
debug
logical, save m_journal::debug =.false. [private]
dp
integer, parameter, private m_journal::dp =kind(0.0d0) [private]
last_int
integer, save m_journal::last_int =0 [private]
secday
real(kind=dp) m_journal::secday =86400.0d0 [private]
stdout
integer, save, private m_journal::stdout =OUTPUT_UNIT [private]