m_verify Module Reference
NAME
M_verify(3fm) - [M_verify] a collection of Fortran routines for supporting code development by providing error processing, debugging procedures and unit testing. (LICENSE:PD)
SYNOPSIS
Functions/Subroutines
subroutine, public unit_check_msg (name, g1, g2, g3, g4, g5, g6, g7, g8, g9)
NAME
unit_check_msg(3f) - [M_verify] converts up to nine standard scalar values to a message for unit testing (LICENSE:PD)
SYNOPSIS
subroutine, public stderr (msg, gen0, gen1, gen2, gen3, gen4, gen5, gen6, gen7, gen8, gen9)
NAME
stderr(3f) - [M_verify] write message to stderr (LICENSE:PD)
SYNOPSIS
subroutine, public fstop (ierr, stdout, stderr)
NAME
fstop(3f) - [M_verify] call stop with both a number and a message (LICENSE:PD)
SYNOPSIS
subroutine, public unit_check (name, logical_expression, msg, msg1, msg2, msg3, msg4, msg5, msg6, msg7, msg8, msg9)
NAME
unit_check(3f) - [M_verify] if logical expression is false, call command `goodbad NAME bad` and stop program by default (LICENSE:PD)
subroutine, public unit_check_start (name, options, msg)
NAME
unit_check_start(3f) - [M_verify] call command `goodbad NAME start` and optionally set options (LICENSE:PD)
subroutine, public unit_check_done (name, opts, msg)
NAME
unit_check_done(3f) - [M_verify] call command `goodbad NAME good` or `goodbad NAME bad` depending on whether failures were found (LICENSE:PD)
subroutine, public unit_check_bad (name, opts, msg)
NAME
unit_check_bad(3f) - [M_verify] call command `goodbad NAME bad` and stop program (LICENSE:PD)
subroutine, public unit_check_good (name, opts, msg)
NAME
unit_check_good(3f) - [M_verify] call command `goodbad NAME good` (LICENSE:PD)
subroutine, public pdec (string)
NAME
pdec(3f) - [M_verify] write out string with ASCII decimal equivalent vertically under it (LICENSE:PD)
function atleast (line, length)
subroutine, public assert (filename, linen, expr, g1, g2, g3, g4, g5, g6, g7, g8, g9)
NAME
assert(3f) - [M_verify] print filename, linenumber, and message to stderr and stop program (LICENSE:PD)
SYNOPSIS
real(kind=realtime) function julian ()
logical function, public almost (x, y, digits, verbose)
NAME
almost(3f) - [M_verify] return true or false if two numbers agree up to specified number of digits (LICENSE:PD)
SYNOPSIS
subroutine, public accdig (X, Y, digi0, ACURCY, IND)
NAME
accdig(3f) - [M_verify] compare two real numbers only up to a specified number of digits (LICENSE:PD)
subroutine, public dp_accdig (x, y, digi0, ACURCY, IND)
NAME
dp_accdig(3f) - [M_verify] compare two numbers only up to a specified number of digits (LICENSE:PD)
elemental pure logical function, public in_margin (expected_value, measured_value, allowed_margin)
NAME
in_margin(3f) - [M_verify] check if two reals are approximately equal using a relative margin
real(kind=dp) function, public round (val, idigits0)
pure elemental real(kind=real128) function anyscalar_to_real128 (valuein)
pure elemental doubleprecision function anyscalar_to_double (valuein)
Variables
integer, save, public io_debug =ERROR_UNIT
integer, save, public unit_check_lun =ERROR_UNIT
logical, save, public debug =.false.
logical, save, public unit_check_keep_going =.false.
integer, save, public unit_check_level =0
character(len=4096), public unit_check_command ='goodbad'
integer, parameter, public realtime =kind(0.0d0)
integer, parameter, public exit_success =0
integer, parameter, public exit_failure =1
real(kind=realtime), save duration =0.0d0
integer, save clicks =0.0d0
logical, save stop_g =.true.
integer, save ipassed_g =0
integer, save ifailed_g =0
logical, save, public no_news_is_good_news =.false.
Detailed Description
NAME
M_verify(3fm) - [M_verify] a collection of Fortran routines for supporting code development by providing error processing, debugging procedures and unit testing. (LICENSE:PD)
SYNOPSIS
use M_verify, only : unit_check, unit_check_start, unit_check_good, unit_check_bad, unit_check_done use M_verify, only : unit_check_limit, unit_check_keep_going, unit_check_command use M_verify, only : unit_check_msg use M_verify, only : debug use M_verify, only : fstop use M_verify, only : stderr use M_verify, only : assert
QUOTE
Do not let your victories go to your head, nor let your failures go to your heart.
DESCRIPTION
The M_verify(3fm) Fortran module provides procedures and variables useful for providing error processing, debugging capabilities, and unit testing.
o allows for a user-defined command to be called to collect results or mail failure alerts, ... o supports easily composing a message from up to nine scalar intrinsic values and different message levels o allows stopping on first failure or continuing
SET MODES unit_check_keep_going logical variable that can be used to turn off program termination on errors. unit_check_level An integer that can be used to specify different debug levels unit_check_command name of command to execute. Defaults to the name `goodbad`. UNIT TESTS unit_check_start(3f) start tests of a procedure and optionally call
                      command NAME start ..."
 unit_check(3f) if expression is false optionally call
                      command NAME bad
                   and stop program (by default)
unit_check_done(3f) call
                      command NAME good
                   if no failures
                   else call
                      command NAME bad
 unit_check_good(3f) call command command NAME good unit_check_bad(3f) call command command NAME bad and stop program by default unit_check_msg(3f) write message
BASIC DEBUGGING fstop(3f) calls 'STOP VALUE' passing in a value (1-32), with optional message pdec(3f) write ASCII Decimal Equivalent (ADE) numbers vertically beneath string stderr(3f) Write message on stderr debug logical variable that can be tested by routines as a flag to process debug statements.
For unit testing, the existence of a command called `goodbad` is initially assumed. This is generally a script that makes entries for each unit in an SQLite data file which is then used to create CSV and HTML reports on the status of each unit. A sample goodbad(1) command written in the bash(1) shell and using the sqlite3(1) command should be included in this distribution as an example
The flexibility introduced by calling an external script or program is that The goodbad(1) command can be changed as desired to write CSV files or simple logs or to notify developers with e-mail as desired.
RELATED FUNCTIONS
The routines in M_verify(3f) are often combined with the M_hashkeys(3fm) routines and various math and statistical routines to quickly create unit tests.
Comparisons of real values can be done with a tolerance with M_Compare_Float_Numbers(3fm), for example.
The intrinsics ANY(3f) and ALL(3f) are particularly useful in calls to unit_check(3f).
EXAMPLES
Sample program
!!program demo_unit_tests module M_demo private public one !! regular routines public two !! regular routines public test_suite_M_demo !! special name for use with test_suite(1bash). contains
!! regular routines subroutine one() end subroutine one
subroutine two() end subroutine two
!! unit test subroutine test_suite_M_demo use M_verify, only: unit_check_start, unit_check use M_verify, only: unit_check_good, unit_check_bad, unit_check_done use M_verify, only: unit_check_msg implicit none integer :: i, j, k integer,allocatable :: array(:) integer :: arr(4)=[21,51,14,45] integer :: a=21, b=51, c=14, d=45 ! TEST-DRIVEN DEVELOPMENT ! optional set-up perform initialization operations common to all tests within a module i=1 j=2 k=3 array=[10,20,30,40,50,60,70] call test_one() call test_two() ! optional tear-down perform finalization operations common to all tests within a module contains
subroutine test_one() ! register an entry for specified name (`one`) in database with status of zero (0) call unit_check_start('one')
! if mask test fails, can ! * produce a SUCCESS: or FAIL: message and stop program ! * change database status for specified entry to -1 and stop program, else continue ! * produce a SUCCESS: or FAIL: message and keep going ! * produce a FAIL: message if test fails but no SUCCESS: message if test passes call unit_check('one',i.gt.0,msg='I > 0')
! using ANY(3f) and ALL(3f) call unit_check('one',all([i,j,k].gt.0), 'testing if everyone greater than zero') ! display message built of scalars as well call unit_check('one',all(.not.[i,j,k].eq.4),'for set ',i,j,k,'testing if no one is equal to four')
! for tests that are hard to reduce to a logical test just call unit_check_bad(3f) if fail if(i+j+k.lt.1)then call unit_check_bad('one') endif
call unit_check_done('one','checks on `one` ended') end subroutine test_one
subroutine test_two ! use of all(3f), any(3f), merge(3f) can be useful ! if you know what these would produce ! write(*,*)['A','X','X','X','X','B'].eq.'B' ! this would return an array, the last element having the value T, else F ! write(*,*)all(['A','X','X','X','X','X'].eq.'X') ! this would return F ! write(*,*)any(['A','X','X','X','X','X'].eq.'B') ! this would return F ! write(*,*)any(['A','X','X','X','X','B'].eq.'B') ! this would return T ! write(*,*).not.all(array.lt.100) ! write(*,*)all(array.lt.100) ! write(*,*)all([a,b,c,d].eq.[21,51,14,45]) ! compare a list. This would return T ! write(*,*)all(arr.eq.[21,51,14,45]) ! compare an array. This would return T ! you know how valuable ANY(3f) and ALL(3f) will be call unit_check_start('two','check on `two` passed') call unit_check('two', 1.gt.0 .and. abs(10.10000-10.10001).lt.0.0001,msg='two looks good') call unit_check_done('two','checks on `two` ended') end subroutine test_two
end subroutine test_suite_M_demo
end module M_demo
program demo_M_verify use M_demo, only: test_suite_M_demo use M_verify, only: unit_check_command, unit_check_keep_going,unit_check_level unit_check_command='' unit_check_keep_going=.true. unit_check_level=0 call test_suite_M_demo end program demo_M_verify
Expected output:
unit_check: one SUCCESS:I > 0 unit_check: one SUCCESS:testing if everyone greater than zero unit_check: one SUCCESS:for set 1 2 3 testing if no one is equal to four unit_check_done: one PASSED GOOD:3 BAD:0
unit_check: two SUCCESS:two looks good unit_check_done: two PASSED GOOD:1 BAD:0
AUTHOR
John S. Urban
LICENSE
Public Domain
Function/Subroutine Documentation
accdig()
subroutine, public m_verify::accdig (real, intent(in) X, real, intent(in) Y, real, intent(in) digi0, real, intent(out) ACURCY, integer, intent(out) IND)
NAME
accdig(3f) - [M_verify] compare two real numbers only up to a specified number of digits (LICENSE:PD)
SYNOPSIS
   subroutine accdig(x,y,digio,acurcy,ind)

    real,intent(in)     :: X
    real,intent(in)     :: Y
    real,intent(in)     :: DIGI0
    real,intent(out)    :: acurcy
    integer,intent(out) :: ind
DESCRIPTION
This procedure is used to check how closely two numbers agree.
call accdig(X,Y,DIGI0,ACURCY,IND)
The values X and Y are the numbers to compare, and DIGI0 is the threshold number of digits to consider significant in returning IND.
If X and Y are considered equal within DIGI0 relative tolerance,
IND    = 0, if tolerance is     satisfied.
       = 1, if tolerance is not satisfied.
The result ACURCY gives a measure of the number of leading digits in X which are the same as the number of leading digits in Y.
    ACURCY=-log10((X-Y)/Y)   if X != Y and Y != 0
    ACURCY=-log10(X-Y)       if X != Y and Y = 0
    ACURCY=8                 if X=Y

    ACURCY is never less than -8 or greater than 8
TOLERANCE ... X and Y are considered equal within DIGI0 relative tolerance, if ACURCY is greater than DIGI0.
For example, Take some numbers and compare then to 1.2345678 ...
 A number | ACURCY | ACURCY
| 1.2345678=Y | 1.2345678=X
1.234680 | 3.7900571 | 3.7901275 1.2345378 | 4.6144510 | 4.6144404 2.2234568 | 0.096367393 | 0.35188114 1.2345678 | 8.0000000 | 8.0000000 1.2345679 | 7.0732967 | 7.0731968 -1.2345678 | -0.30103000 | -0.30103000 76.234567 | -1.7835463 | 0.0070906729 2.4691356 | 0.0 | 0.3010300 0.0 | 0.0 | -0.91514942.
Due to the typical limits of the log function, the number of significant digits in the result is best considered to be three.
Notice that 1.2345678=Y produces different values than 1.2345678=X
A negative result indicates the two values being compared either do not agree in the first digit or they differ with respect to sign. An example of two numbers which do not agree in their leading digit (and actually differ in order of magnitude) is given above by X=76.234567 and Y=1.2345678; the accuracy reported is -1.7835463. An example of two numbers which do not agree in sign in X=-1.2345678 and Y=1.2345678; here the accuracy reported is -0.30103000.
EXAMPLE
Example program:
program demo_accdig ! fortran 90 example use M_verify, only : accdig implicit none integer :: digi integer :: i10, i20, i30 integer :: ind, ind1, ind2 real :: acurcy, acurcy1, acurcy2 real :: a, b real :: vals(9) data vals/ & &1.234680, 1.2345378, 2.2234568, 1.2345678, & &1.2345679, -1.2345678, 76.234567, 2.4691356, & &0.0/ write(*,*)'=========================' do i10=0,16 a=1.0 b=a+1.0/(10**i10) call accdig(a,b,8.0,acurcy,ind) write(*,*)i10,a,b,acurcy,ind enddo write(*,*)'=========================' digi=16 do i20=0,digi a=1.0 b=a+1.0/(10**i20) call accdig(a,b,real(digi),acurcy,ind) write(*,*)i20,a,b,acurcy,ind enddo write(*,*)'=========================' do i30=1,9 call accdig(1.2345678,vals(i30),8.0,acurcy1,ind1) call accdig(vals(i30),1.2345678,8.0,acurcy2,ind2) write(*,*)i30,vals(i30),acurcy1,acurcy2,ind1,ind2 enddo end program demo_accdig
REFERENCES
based on ...
NBS OMNITAB 1980 VERSION 6.01 1/ 1/81. accdig V 7.00 2/14/90. ** David Hogben, Statistical Engineering Division, Center for Computing and Applied Mathematics, A337 Administration Building, National Institute of Standards and Technology, Gaithersburg, MD 20899 TELEPHONE 301-975-2845 ORIGINAL VERSION - October, 1969. CURRENT VERSION - February, 1990. JSU VERSION - February, 1991.
DEPENDENCIES
o M_journal(),log10(), abs(1)
AUTHOR
David Hogben, John S. Urban
LICENSE
Public Domain Here is the caller graph for this function:
almost()
logical function, public m_verify::almost (class(*), intent(in) x, class(*), intent(in) y, class(*), intent(in) digits, logical, intent(in), optional verbose)
NAME
almost(3f) - [M_verify] return true or false if two numbers agree up to specified number of digits (LICENSE:PD)
SYNOPSIS
function almost(x,y,digits)
class(*),intent(in) :: x,y class(*),intent(in) :: rdigits logical,intent(in),optional :: verbose logical :: almost
DESCRIPTION
Returns true or false depending on whether the two numbers given agree to within the specified number of digits as calculated by ACCDIG(3f).
OPTIONS
x,y expected and calculated values to be compared. May be of type REAL, INTEGER, or DOUBLEPRECISION. rdigits real number representing number of digits of precision to compare verbose optional value that specifies to print the results of the comparison when set to .TRUE..
RETURNS
almost TRUE if the input values compare up to the specified number of values
EXAMPLE
sample:
program demo_almost use M_verify, only : almost real :: x, y logical :: z x=1.2345678 y=1.2300000 do i=1,8 z=almost(x,y,real(i),verbose=.true.) write(*,*)i,z enddo end program demo_almost
output:
almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 1.0 1 T almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 2.0 2 T almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 3.0 3 F almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 4.0 4 F almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 5.0 5 F almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 6.0 6 F almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 7.0 7 F accdig significant digit request too high= 8.00000000 almost for values 1.23456776 1.23000002 agreement of 2.43020344 digits out of requested 8.0 8 F
AUTHOR
John S. Urban
LICENSE
Public Domain
References accdig(), anyscalar_to_real128(), and dp_accdig().
anyscalar_to_double()
pure elemental doubleprecision function m_verify::anyscalar_to_double (class(*), intent(in) valuein) [private]
anyscalar_to_real128()
pure elemental real(kind=real128) function m_verify::anyscalar_to_real128 (class(*), intent(in) valuein) [private]
assert()
subroutine, public m_verify::assert (character(len=*), intent(in) filename, integer, intent(in) linen, logical, intent(in) expr, class(*), intent(in), optional g1, class(*), intent(in), optional g2, class(*), intent(in), optional g3, class(*), intent(in), optional g4, class(*), intent(in), optional g5, class(*), intent(in), optional g6, class(*), intent(in), optional g7, class(*), intent(in), optional g8, class(*), intent(in), optional g9)
NAME
assert(3f) - [M_verify] print filename, linenumber, and message to stderr and stop program (LICENSE:PD)
SYNOPSIS
function assert(file,linenum,expr,g1,g2g3,g4,g5,g6,g7,g8,g9)
character(len=*),intent(in) :: file character(len=*),intent(in) :: linenum logical,intent(in) :: expr class(*),intent(in),optional :: g1,g2,g3,g4,g5,g6,g7,g8,g9
DESCRIPTION
assert(3f) prints strings to stderr and then stops program with exit code 1 It labels the first string as the filename, the next integer parameter as the linenumber, and then up to nine scalar values.
It is primarily intended for use by the ufpp(1) preprocessor $ASSERT directive
OPTIONS
filename   a string assumed to be the current filename when compiling
linenum    assumed to be the line number of the source code the ASSERT(3f)
           procedure was called at.
expr       logical value
g[1-9]  optional value(s) to print as a message before stopping. May
        be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX,
        or CHARACTER.
EXAMPLES
Sample program:
program demo_assert use M_verify, only : assert implicit none real :: a, toobig=1024 a=2000 call assert('myroutine', 101, a.gt.toobig, 'The value is too large', a, '.gt.', toobig) end program demo_assert
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
atleast()
function m_verify::atleast (character(len=*), intent(in) line, integer, intent(in) length) [private]
dp_accdig()
subroutine, public m_verify::dp_accdig (class(*), intent(in) x, class(*), intent(in) y, class(*), intent(in) digi0, real, intent(out) ACURCY, integer, intent(out) IND)
NAME
dp_accdig(3f) - [M_verify] compare two numbers only up to a specified number of digits (LICENSE:PD)
SYNOPSIS
   subroutine dp_accdig(x,y,digio,acurcy,ind)

    class(*),intent(in)  :: X
    class(*),intent(in)  :: Y
    class(*),intent(in)  :: DIGI0
    real,intent(out)     :: acurcy
    integer,intent(out)  :: ind
DESCRIPTION
This procedure is used to check how closely two numbers agree.

   call dp_accdig(X,Y,DIGI0,ACURCY,IND)

The values X and Y are the numbers to compare, and DIGI0 is the
threshold number of digits to consider significant in returning IND.

If X and Y are considered equal within DIGI0 relative tolerance,

    IND    = 0, if tolerance is     satisfied.
           = 1, if tolerance is not satisfied.

The result ACURCY gives a measure of the number of leading digits in X
which are the same as the number of leading digits in Y.

     ACURCY=-log10((X-Y)/Y)   if X != Y and Y != 0
     ACURCY=-log10(X-Y)       if X != Y and Y = 0
     ACURCY=8                 if X=Y

     ACURCY is never less than -8 or greater than 8 for REAL values

TOLERANCE ...
     X and Y are considered equal within DIGI0 relative tolerance,
     if ACURCY is greater than DIGI0.

For example, Take some numbers and compare then  to 1.2345678 ...

   ================================================
   A number     |    ACURCY       |   ACURCY
                |    1.2345678=Y  |   1.2345678=X
   ================================================
    1.234680    |    3.7900571    |   3.7901275
    1.2345378   |    4.6144510    |   4.6144404
    2.2234568   |    0.096367393  |   0.35188114
    1.2345678   |    8.0000000    |   8.0000000
    1.2345679   |    7.0732967    |   7.0731968
   -1.2345678   |   -0.30103000   |  -0.30103000
   76.234567    |   -1.7835463    |   0.0070906729
    2.4691356   |    0.0          |   0.3010300
    0.0         |    0.0          |  -0.91514942.

Due to the typical limits of the log function, the number of
significant digits in the result is best considered to be three.

Notice that 1.2345678=Y produces different values than 1.2345678=X

A negative result indicates the two values being compared either do
not agree in the first digit or they differ with respect to sign. An
example of two numbers which do not agree in their leading digit (and
actually differ in order of magnitude) is given above by X=76.234567
and Y=1.2345678; the accuracy reported is -1.7835463. An example of
two numbers which do not agree in sign in X=-1.2345678 and Y=1.2345678;
here the accuracy reported is -0.30103000.
EXAMPLE
Example program:
program demo_dp_accdig ! fortran 90 example use M_verify, only : dp_accdig implicit none integer :: digi doubleprecision :: a, b integer :: i10, i20, i30 integer :: ind, ind1, ind2 real :: acurcy, acurcy1, acurcy2 doubleprecision :: vals(9) data vals/ & &1.234680d0, 1.2345378d0, 2.2234568d0, 1.2345678d0, & &1.2345679d0, -1.2345678d0, 76.234567d0, 2.4691356d0, & &0.0d0/ write(*,*)'=========================' do i10=0,16 a=1.0d0 b=a+1.0d0/(10**i10) call dp_accdig(a,b,8.0,acurcy,ind) write(*,*)i10,a,b,acurcy,ind enddo write(*,*)'=========================' digi=16 do i20=0,digi a=1.0d0 b=a+1.0d0/(10**i20) call dp_accdig(a,b,dble(digi),acurcy,ind) write(*,*)i20,a,b,acurcy,ind enddo write(*,*)'=========================' do i30=1,9 call dp_accdig(1.2345678d0,vals(i30),8.0,acurcy1,ind1) call dp_accdig(vals(i30),1.2345678d0,8.0,acurcy2,ind2) write(*,*)i30,vals(i30),acurcy1,acurcy2,ind1,ind2 enddo end program demo_dp_accdig
NOTES
REFERENCES
based on ...
NBS OMNITAB 1980 VERSION 6.01 1/ 1/81. dp_accdig V 7.00 2/14/90. ** David Hogben, Statistical Engineering Division, Center for Computing and Applied Mathematics, A337 Administration Building, National Institute of Standards and Technology, Gaithersburg, MD 20899 TELEPHONE 301-975-2845 ORIGINAL VERSION - October, 1969. CURRENT VERSION - February, 1990. JSU VERSION - February, 1991.
DEPENDENCIES
o M_journal(), log10(), abs(1)
AUTHORS
David Hogben, John S. Urban
LICENSE
Public Domain
References anyscalar_to_real128().
fstop()
subroutine, public m_verify::fstop (integer, intent(in) ierr, character(len=*), intent(in), optional stdout, character(len=*), intent(in), optional stderr)
NAME
fstop(3f) - [M_verify] call stop with both a number and a message (LICENSE:PD)
SYNOPSIS
subroutine fstop(ierr,stdout,stderr)
integer,intent(in) :: ierr character(len=*),intent(in),optional :: stdout character(len=*),intent(in),optional :: stderr
DESCRIPTION
FSTOP(3f) call STOP(3f). What a call to STOP does is very system dependent, so using an abstraction layer is useful, as it allows just the fstop() routine to be changed; and STOP does not allow a variable to be used on the numeric access status (this has changed at f2015).
OPTIONS
ierr - value in range 0 to 32 stdout - description to be printed to standard output stderr - description to be printed to standard error
EXAMPLES
Sample program:
program demo_fstop use M_verify, only: fstop implicit none integer :: int !*!write(*,*)'Enter stop value' !*!read(*,*) int int=25 select case(int) case(10) ; call fstop(int) case(20) ; call fstop(int,stderr='error: program will now stop') case(25) ; call fstop(int,stdout='stdout message',stderr='stderr message') case(30) ; call fstop(int,stdout='error: program will now stop') case default call fstop(int) endselect
end program demo_fstop
Results:
SEE ALSO
Look for common extensions, such as abort(3f), backtrace(3f)
AUTHOR
John S. Urban
LICENSE
Public Domain
References stderr().
in_margin()
elemental pure logical function, public m_verify::in_margin (class(*), intent(in) expected_value, class(*), intent(in) measured_value, class(*), intent(in) allowed_margin)
NAME
in_margin(3f) - [M_verify] check if two reals are approximately equal using a relative margin
SYNOPSIS
 elemental pure function in_margin( expected_value, measured_value, allowed_margin )

  real, intent(in)    :: expected_value
  real, intent(in)    :: measured_value
  real, intent(in)    :: allowed_margin
  class(*),intent(in) :: invalue
DESCRIPTION
Compare two values to see if they are relatively equal using the specified allowed margin. That is, see if VALUE_MEASURED is in the range VALUE_EXPECTED +- ALLOWED_ERROR where the allowed error varies with the magnitude of the values, such that the allowed error is margin * average magnitude of measured and expected).
So the allowed error is smaller when the magnitudes are smaller.
OPTIONS
expected_value First value measured_value Second value allowed_margin Allowed relative margin
EXAMPLE
Sample program:
program demo_in_margin use :: M_verify, only : in_margin implicit none write(*,*) in_margin(4.00000,3.99999,0.000000001) write(*,*) in_margin(4.00000,3.99999,0.00000001) write(*,*) in_margin(4.00000,3.99999,0.0000001) write(*,*) in_margin(4.00000,3.99999,0.000001)
write(*,*) in_margin([4.0,40.0,400.0,4000.0,40000.0], [3.9,39.9,399.9,3999.9,39999.9] ,0.000001) write(*,*) in_margin([4.0,40.0,400.0,4000.0,40000.0], [3.9,39.9,399.9,3999.9,39999.9] ,0.00001)
write(*,*) in_margin(4.00000,3.99999,0.00001) write(*,*) in_margin(4.00000,3.99999,0.0001) write(*,*) in_margin(4.00000,3.99999,0.001) write(*,*) in_margin(4.00000,3.99999,0.01)
end program demo_in_margin
Results:
F F F F F F F F F F F F F T T T T T
References anyscalar_to_double().
julian()
real(kind=realtime) function m_verify::julian () [private]
pdec()
subroutine, public m_verify::pdec (character(len=*), intent(in) string)
NAME
pdec(3f) - [M_verify] write out string with ASCII decimal equivalent vertically under it (LICENSE:PD)
SYNOPSIS
Usage:

 subroutine pdec(string)
 character(len=*),intent(in) :: string
DESCRIPTION
Given a string to print, PDEC() writes out the ASCII Decimal equivalent
of the string directly underneath it. This can help you to locate
unprintable characters or non-standard white-space such as a backspace
character or tab character in input strings that your program could
not interpret. On output, non-printable characters are replaced with
a space, and trailing spaces are ignored.

You read the numbers vertically.

1. ignore trailing spaces
2. print the character if it has an ADE of 32 on up
3. print a space if it has an ADE of less than 32
4. underneath each character print the ADE value vertically
5. strings are assumed under 32767 characters in length.
   Format integer constants > 32767 are not supported on HP-UX
   when newer compilers are available use unlimited
EXAMPLES
Sample program:

   program demo_pdec
   use M_verify, only : pdec
   call pdec(' ABCDEFG abcdefg    ')
   end program demo_pdec

would produce (notice trailing space is trimmed):

  > ABCDEFG abcdefg
  >0000000000001111
  >3666667739990000
  >2567890127890123
AUTHOR
John S. Urban
LICENSE
Public Domain
round()
real(kind=dp) function, public m_verify::round (real(kind=dp), intent(in) val, integer, intent(in) idigits0)
stderr()
subroutine, public m_verify::stderr (class(*), intent(in), optional msg, class(*), intent(in), optional gen0, class(*), intent(in), optional gen1, class(*), intent(in), optional gen2, class(*), intent(in), optional gen3, class(*), intent(in), optional gen4, class(*), intent(in), optional gen5, class(*), intent(in), optional gen6, class(*), intent(in), optional gen7, class(*), intent(in), optional gen8, class(*), intent(in), optional gen9)
NAME
stderr(3f) - [M_verify] write message to stderr (LICENSE:PD)
SYNOPSIS
subroutine stderr(msg,[generic])
class(*),intent(in),optional :: msg class(*),intent(in),optional :: generic0,generic1,generic2,generic3,generic4 class(*),intent(in),optional :: generic5,generic6,generic7,generic8,generic9
DESCRIPTION
STDERR(3f) writes a message to standard error using a standard f2003 method. Up to ten generic options are available.
OPTIONS
msg - description to print generic[0-9] - optional value to print the value of after the message. May be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX, or CHARACTER.
EXAMPLES
Sample program:
program demo_stderr use,intrinsic :: iso_fortran_env, only : int8, int16, int32, int64 use,intrinsic :: iso_fortran_env, only : real32, real64, real128 use,intrinsic :: iso_fortran_env, only : real=> real32, integer=> int32 use M_verify, only: stderr implicit none
call stderr('A simple message') call stderr('error: RVALUE=',3.0/4.0) call stderr('error: IVALUE=',123456789) call stderr('error: LVALUE=',.true.)
SEVERAL: block integer :: least=10, most=999, ival=-10 call stderr('error: value',ival,'should be between',least,'and',most) endblock SEVERAL
call stderr('real32 :',huge(0.0_real32),0.0_real32,12345.6789_real32,tiny(0.0_real32)) call stderr('real64 :',huge(0.0_real64),0.0_real64,12345.6789_real64,tiny(0.0_real64)) call stderr('real128 :',huge(0.0_real128),0.0_real128,12345.6789_real128,tiny(0.0_real128)) call stderr('complex :',cmplx(huge(0.0_real),tiny(0.0_real)))
call stderr('error: program will now stop') stop 1
end program demo_stderr
Results: A simple message error: RVALUE= 0.750000000 error: IVALUE= 123456789 error: LVALUE= T error: value -10 should be between 10 and 999 real32 : 3.40282347E+38 ... 0.00000000 ... 12345.6787 ... 1.17549435E-38 real64 : 1.7976931348623157E+308 ... 0.0000000000000000 ... 12345.678900000001 ... 2.2250738585072014E-308 real128 : 1.18973149535723176508575932662800702E+4932 ... 0.00000000000000000000000000000000000 ... 12345.6789000000000000000000000000002 ... 3.36210314311209350626267781732175260E-4932 complex : (3.40282347E+38,1.17549435E-38) error: program will now stop
STOP 1
AUTHOR
John S. Urban
LICENSE
Public Domain Here is the caller graph for this function:
unit_check()
subroutine, public m_verify::unit_check (character(len=*), intent(in) name, logical, intent(in) logical_expression, class(*), intent(in), optional msg, class(*), intent(in), optional msg1, class(*), intent(in), optional msg2, class(*), intent(in), optional msg3, class(*), intent(in), optional msg4, class(*), intent(in), optional msg5, class(*), intent(in), optional msg6, class(*), intent(in), optional msg7, class(*), intent(in), optional msg8, class(*), intent(in), optional msg9)
NAME
unit_check(3f) - [M_verify] if logical expression is false, call command `goodbad NAME bad` and stop program by default (LICENSE:PD)
SYNOPSIS
subroutine unit_check(name,expression,msg,msg1,msg2,msg3,msg4,msg5,msg6,msg7,msg8,msg9)

 character(len=*),intent(in) :: name
 logical,intent(in) :: expression
 class(*),intent(in),optional :: msg,msg1,msg2,msg3,msg4,msg5,msg6,msg7,msg8,msg9
DESCRIPTION
unit_check(3f) tests the expression and if it is false, calls the shell command
 goodbad NAME bad
and stops the program.
OPTIONS
NAME the unit test name passed on to the goodbad(1) command EXPRESSION the logical expression to evaluate MSG,MSG1...MSG9 optional message to display when performing test, composed of any scalar intrinsics of type INTEGER, REAL, DOUBLEPRECISION, COMPLEX, LOGICAL, or CHARACTER, with a space placed between each value.
EXAMPLES
Sample program:
program demo_unit_check use M_verify, only: unit_check use M_verify, only: unit_check_start use M_verify, only: unit_check_done use M_verify, only: almost
!!use M_verify, only: unit_check_keep_going ! default is unit_check_keep_going=.false. !!use M_verify, only: debug ! default is .false. !!use M_verify, only: unit_check_command ! default is unit_check_command='goodbad'
implicit none integer :: i integer :: x integer,allocatable :: arr(:) real,allocatable :: arr1(:) real,allocatable :: arr2(:)
!!unit_check_command='' x=10 arr1=[1.0,10.0,100.0] arr2=[1.0001,10.001,100.01] call unit_check_start('myroutine')
call unit_check('myroutine', x.gt.3 ,'test if big enough') call unit_check('myroutine', x.lt.100 ,'test if small enough')
do i=1,size(arr1) call unit_check('myroutine', almost(arr1(i),arr2(i),3.9,verbose=.true.)) enddo
arr=[10,20,30] call unit_check('myroutine', .not.any(arr.lt.0) ,'test if any negative values in array ARR') call unit_check('myroutine', all(arr.lt.100) ,'test if all values less than 100 in array ARR')
call unit_check_done('myroutine',msg='checks on `myroutine` all passed')
end program demo_unit_check
Sample output (varies with what goodbad(1) command is used):
unit_check: myroutine SUCCESS:test if big enough unit_check: myroutine SUCCESS:test if small enough unit_check: myroutine SUCCESS:test if any negative values in array ARR unit_check: myroutine SUCCESS:test if all values less than 100 in array ARR almost for values 1.00000000 1.00010002 agreement of 3.99997139 digits out of requested 3.90000010 almost for values 10.0000000 10.0010004 agreement of 3.99986792 digits out of requested 3.90000010 almost for values 100.000000 100.010002 agreement of 3.99995065 digits out of requested 3.90000010 unit_check_good: myroutine PASSED:checks on `myroutine` all passed
AUTHOR
John S. Urban
LICENSE
Public Domain
References atleast(), fstop(), ifailed_g, ipassed_g, no_news_is_good_news, stderr(), unit_check_command, and unit_check_keep_going.
unit_check_bad()
subroutine, public m_verify::unit_check_bad (character(len=*), intent(in) name, character(len=*), intent(in), optional opts, character(len=*), intent(in), optional msg)
NAME
unit_check_bad(3f) - [M_verify] call command `goodbad NAME bad` and stop program (LICENSE:PD)
SYNOPSIS
subroutine unit_check_bad(name,opts,msg)

 character(len=*),intent(in) :: name
 character(len=*),intent(in),optional :: opts
 character(len=*),intent(in),optional :: msg
DESCRIPTION
unit_check_bad(3f) calls the shell command

     goodbad NAME bad [opts]

and stops the program. It is just a shortcut for calling
     call unit_check(name,.false.)
     call unit_check_done(name,opts,msg)
EXAMPLES
Sample program:
program demo_unit_check_bad use M_verify, only: unit_check_start use M_verify, only: unit_check use M_verify, only: unit_check_good, unit_check_bad
implicit none integer :: x x=10 call unit_check_start('myroutine')
call unit_check('myroutine', x.gt.3 ,'test if big enough') call unit_check('myroutine', x.lt.100 ,'test if small enough')
if(x.ne.0)then call unit_check_bad ('myroutine',msg='checks on `myroutine` failed') ! program execution stopped endif
end program demo_unit_check_bad
AUTHOR
John S. Urban
LICENSE
Public Domain
References unit_check(), and unit_check_done().
unit_check_done()
subroutine, public m_verify::unit_check_done (character(len=*), intent(in) name, character(len=*), intent(in), optional opts, character(len=*), intent(in), optional msg)
NAME
unit_check_done(3f) - [M_verify] call command `goodbad NAME good` or `goodbad NAME bad` depending on whether failures were found (LICENSE:PD)
SYNOPSIS
subroutine unit_check_done(name,opts,msg)

 character(len=*),intent(in) :: name
 character(len=*),intent(in),optional :: opts
 character(len=*),intent(in),optional :: msg
DESCRIPTION
If there have been no failures the shell command

     goodbad NAME good [opts]

is executed, else the command

     goodbad NAME bad [opts]

is executed and by default stops the program if their have been
any failures.
EXAMPLES
Sample program:
program demo_unit_check_done use M_verify, only: unit_check_start use M_verify, only: unit_check use M_verify, only: unit_check_good, unit_check_done, unit_check_bad
implicit none integer :: x x=10 call unit_check_start('myroutine')
call unit_check('myroutine', x.gt.3 ,'test if big enough') call unit_check('myroutine', x.lt.100 ,'test if small enough')
if(x.ne.0)then call unit_check_done ('myroutine',msg='checks on `myroutine`') ! program execution stopped endif
end program demo_unit_check_done
AUTHOR
John S. Urban
LICENSE
Public Domain
References atleast(), clicks, duration, fstop(), ifailed_g, ipassed_g, julian(), stderr(), unit_check_command, and unit_check_keep_going.
unit_check_good()
subroutine, public m_verify::unit_check_good (character(len=*), intent(in) name, character(len=*), intent(in), optional opts, character(len=*), intent(in), optional msg)
NAME
unit_check_good(3f) - [M_verify] call command `goodbad NAME good` (LICENSE:PD)
SYNOPSIS
subroutine unit_check_good(name,opts,msg)

 character(len=*),intent(in)          :: name
 character(len=*),intent(in),optional :: opts
 character(len=*),intent(in),optional :: msg
DESCRIPTION
A shortcut for
call unit_check(name,.true.) call unit_check_done(name,opts,msg)
EXAMPLES
Sample program:
program demo_unit_check_good use M_verify, only: unit_check_start, unit_check_done use M_verify, only: unit_check use M_verify, only: unit_check_good, unit_check_bad
implicit none integer :: x x=10 call unit_check_start('myroutine')
call unit_check('myroutine', x.gt.3 ,'test if big enough') call unit_check('myroutine', x.lt.100 ,'test if small enough')
call unit_check_good('myroutine',msg='checks on `myroutine` ')
end program demo_unit_check_good
AUTHOR
John S. Urban
LICENSE
Public Domain
References unit_check(), and unit_check_done().
unit_check_msg()
subroutine, public m_verify::unit_check_msg (character(len=*), intent(in) name, class(*), intent(in), optional g1, class(*), intent(in), optional g2, class(*), intent(in), optional g3, class(*), intent(in), optional g4, class(*), intent(in), optional g5, class(*), intent(in), optional g6, class(*), intent(in), optional g7, class(*), intent(in), optional g8, class(*), intent(in), optional g9)
NAME
unit_check_msg(3f) - [M_verify] converts up to nine standard scalar values to a message for unit testing (LICENSE:PD)
SYNOPSIS
function unit_check_msg(name,g1,g2g3,g4,g5,g6,g7,g8,g9)
character(len=*),intent(in) :: name class(*),intent(in),optional :: g1,g2,g3,g4,g5,g6,g7,g8,g9
DESCRIPTION
unit_check_msg(3f) builds a string from up to nine scalar values and prints it to the error long.
OPTIONS
name name of unit being tested g[1-9] optional value to print the value of after the message. May be of type INTEGER, LOGICAL, REAL, DOUBLEPRECISION, COMPLEX, or CHARACTER.
EXAMPLES
Sample program:
program demo_unit_check_msg use M_verify, only : unit_check_start,unit_check_msg,unit_check_done implicit none
call unit_check_start('myroutine') call unit_check_msg('myroutine','HUGE(3f) integers',huge(0),'and real',huge(0.0),'and double',huge(0.0d0)) call unit_check_msg('myroutine','real :',huge(0.0),0.0,12345.6789,tiny(0.0)) call unit_check_msg('myroutine','doubleprecision :',huge(0.0d0),0.0d0,12345.6789d0,tiny(0.0d0)) call unit_check_msg('myroutine','complex :',cmplx(huge(0.0),tiny(0.0))) call unit_check_done('myroutine')
end program demo_unit_check_msg
AUTHOR
John S. Urban
LICENSE
Public Domain
References atleast(), and stderr().
unit_check_start()
subroutine, public m_verify::unit_check_start (character(len=*), intent(in) name, character(len=*), intent(in), optional options, character(len=*), intent(in), optional msg)
NAME
unit_check_start(3f) - [M_verify] call command `goodbad NAME start` and optionally set options (LICENSE:PD)
SYNOPSIS
subroutine unit_check_start(name,options,msg)

 character(len=*),intent(in)          :: name
 character(len=*),intent(in),optional :: options
 character(len=*),intent(in),optional :: msg
DESCRIPTION
unit_check_start(3f) is an initialization command that by default calls the shell command
goodbad NAME start [options]
The command can be changed by setting the environment variable UNIT_CHECK_COMMAND or the global module variable UNIT_CHECK_COMMAND. The environment variable overrides the global module variable.
By default if a unit_check(3f) logical expression is false or the unit_check_bad(3f) procedure is called the program will be stopped.
This has the same effect as setting the environment variable M_verify_STOP to `FALSE` or the global module variable UNIT_CHECK_KEEP_GOING to .FALSE. . Set the value to .true. and the program will continue even when tests fail.
OPTIONS
NAME name of the shell command to execute. If blank, no command is executed. OPTIONS pass additional options to the shell command
MSG print message
EXAMPLES
Sample program:
program demo_unit_check_start use M_verify, only: unit_check_start use M_verify, only: unit_check use M_verify, only: unit_check_done
implicit none integer :: ival call unit_check_start('myroutine') ! the goodbad(1) command called here takes many options ! used to build an SQLite3 entry call unit_check_start('myroutine_long',' & & -section 3 & & -library libGPF & & -filename pwd/M_verify.FF & & -documentation y & & -ufpp y & & -ccall n & & -archive GPF.a & & ')
ival=10 call unit_check('myroutine', ival.gt.3 , msg='test if big enough') call unit_check('myroutine', ival.lt.100 , msg='test if small enough')
call unit_check_done('myroutine',msg='completed checks of `myroutine`')
end program demo_unit_check_start
AUTHOR
John S. Urban
LICENSE
Public Domain
References atleast(), clicks, duration, ifailed_g, ipassed_g, julian(), stderr(), unit_check_command, and unit_check_keep_going.
Variable Documentation
clicks
integer, save m_verify::clicks =0.0d0 [private]
debug
logical, save, public m_verify::debug =.false.
duration
real(kind=realtime), save m_verify::duration =0.0d0 [private]
exit_failure
integer, parameter, public m_verify::exit_failure =1
exit_success
integer, parameter, public m_verify::exit_success =0
ifailed_g
integer, save m_verify::ifailed_g =0 [private]
io_debug
integer, save, public m_verify::io_debug =ERROR_UNIT
ipassed_g
integer, save m_verify::ipassed_g =0 [private]
no_news_is_good_news
logical, save, public m_verify::no_news_is_good_news =.false.
realtime
integer, parameter, public m_verify::realtime =kind(0.0d0)
stop_g
logical, save m_verify::stop_g =.true. [private]
unit_check_command
character(len=4096), public m_verify::unit_check_command ='goodbad'
unit_check_keep_going
logical, save, public m_verify::unit_check_keep_going =.false.
unit_check_level
integer, save, public m_verify::unit_check_level =0
unit_check_lun
integer, save, public m_verify::unit_check_lun =ERROR_UNIT