m_time Module Reference
Functions/Subroutines
subroutine, public d2j (dat, julian, ierr)
subroutine, public j2d (dat, julian, ierr)
subroutine, public d2u (dat, unixtime, ierr)
subroutine, public u2d (dat, unixtime, ierr)
integer function, public d2o (dat)
character(len=:) function, allocatable, public v2mo (imonth)
character(len=:) function, allocatable, public now (format)
character(len=:) function, allocatable, public fmtdate (values, format)
subroutine, public fmtdate_usage (ii)
subroutine, public dow (values, weekday, day, ierr)
subroutine, public woy (dat, iso_year, iso_week, iso_weekday, iso_name)
real(kind=dp) function, public dj (dat)
integer function, dimension(8), public jd (julian)
real(kind=dp) function, public du (dat)
integer function, dimension(8), public ud (unixtime)
subroutine, public sys_sleep (wait_seconds)
Variables
integer, parameter, private dp =kind(0.0d0)
real(kind=dp) secday =86400.0d0
Function/Subroutine Documentation
d2j()
subroutine, public m_time::d2j (integer, dimension(8), intent(in) dat, real(kind=dp), intent(out) julian, integer, intent(out) ierr)
d2o()
integer function, public m_time::d2o (integer, dimension(8), intent(in) dat)
References d2u(), and secday.
d2u()
subroutine, public m_time::d2u (integer, dimension(8), intent(in) dat, real(kind=dp), intent(out) unixtime, integer, intent(out) ierr)
References d2j(), and secday.
dj()
real(kind=dp) function, public m_time::dj (integer, dimension(8), intent(in) dat)
References d2j().
dow()
subroutine, public m_time::dow (integer, dimension(8), intent(in) values, integer, intent(out), optional weekday, character*(*), intent(out), optional day, integer, intent(out) ierr)
References d2j().
du()
real(kind=dp) function, public m_time::du (integer, dimension(8), intent(in) dat)
References d2u().
fmtdate()
character(len=:) function, allocatable, public m_time::fmtdate (integer, dimension(8), intent(in) values, character(len=*), intent(in) format)
References d2j(), d2o(), d2u(), dow(), v2mo(), and woy().
fmtdate_usage()
subroutine, public m_time::fmtdate_usage (integer ii)
j2d()
subroutine, public m_time::j2d (integer, dimension(8), intent(out) dat, real(kind=dp), intent(in) julian, integer, intent(out) ierr)
References jd(), and secday.
jd()
integer function, dimension(8), public m_time::jd (real(kind=dp), intent(in) julian)
References j2d().
now()
character(len=:) function, allocatable, public m_time::now (character(len=*), intent(in), optional format)
References fmtdate().
sys_sleep()
subroutine, public m_time::sys_sleep (integer (c_int) wait_seconds)
u2d()
subroutine, public m_time::u2d (integer, dimension(8), intent(out) dat, real(kind=dp), intent(in) unixtime, integer, intent(out) ierr)
References d2j(), j2d(), and secday.
ud()
integer function, dimension(8), public m_time::ud (real(kind=dp), intent(in) unixtime)
References u2d().
v2mo()
character(len=:) function, allocatable, public m_time::v2mo (integer, intent(in) imonth)
woy()
subroutine, public m_time::woy (integer, dimension(8), intent(in) dat, integer, intent(out) iso_year, integer, intent(out) iso_week, integer, intent(out) iso_weekday, character(len=10), intent(out) iso_name)
References uncorrected_week_of_year().
Variable Documentation
dp
integer, parameter, private m_time::dp =kind(0.0d0) [private]
secday
real(kind=dp) m_time::secday =86400.0d0 [private]